// src/presentation/components/Card.vue
<script setup lang="ts">
import type { CountrySummary } from '../../core/domain/Country';
import ImageLazy from './ImageLazy.vue';
import { useFormatting } from '../../core/domain/useFormatting';
import { UI_LABELS } from '../../core/constants/uiLabels';

const props = defineProps<{
  country: CountrySummary;
  index?: number;
}>();

defineEmits<{
  country: [country: CountrySummary];
  load: [data: { loadButton: boolean }];
}>();

const { formatNumber } = useFormatting();
const countryCode = props.country.cca3.toLowerCase();
const isAboveFold = props.index !== undefined && props.index < 8;
</script>

<template>
  <a 
    :href="`/detail/${countryCode}`"
    class="block bg-surface border border-muted/10 rounded overflow-hidden shadow-sm hover:-translate-y-2 hover:shadow-md transition-all duration-300 relative group"
  >
    <div class="absolute top-0 left-0 right-0 h-1 bg-linear-to-r from-muted to-muted/50 opacity-0 group-hover:opacity-100 transition-opacity z-10" />

    <div class="aspect-3/2 bg-muted/20 relative overflow-hidden">
      <ImageLazy
        :countryFlag="country.flags.svg"
        :countryAlt="country.flags.alt || country.common"
        :priority="isAboveFold"
      />
    </div>

    <div class="p-6 pb-8">
      <h2 class="text-lg font-extrabold text-text mb-4 leading-tight drop-shadow-sm line-clamp-1" :title="country.common">
        {{ country.common }}
      </h2>

      <div class="flex flex-col gap-2">
        <div class="flex items-baseline gap-1 text-[14px]">
          <span class="font-semibold text-text">{{ UI_LABELS.POPULATION }}</span>
          <span class="text-text font-light">{{ formatNumber(country.population) }}</span>
        </div>
        
        <div class="flex items-baseline gap-1 text-[14px]">
          <span class="font-semibold text-text">{{ UI_LABELS.REGION }}</span>
          <span class="text-text font-light">{{ country.region }}</span>
        </div>
        
        <div class="flex items-baseline gap-1 text-[14px]">
          <span class="font-semibold text-text">{{ UI_LABELS.CAPITAL }}</span>
          <span class="text-text font-light truncate" :title="country.capital.join(', ')">
            {{ country.capital?.length ? country.capital.join(', ') : 'None' }}
          </span>
        </div>
      </div>
    </div>
  </a>
</template>

// src/lib/Card.svelte
<script>
	import { fade } from 'svelte/transition';
	import ImageLazy from './ImageLazy.svelte';
	import { createEventDispatcher } from 'svelte';
	export let country;
	const dispatch = createEventDispatcher();
	const nameCountry = country.name.common.split(' ').join('_');
</script>
<div>
	<button transition:fade on:load={() => (dispatch('load',{loadButton: true}))} class="w-[270px] h-[350px] bg-white dark:bg-menu-color-dark rounded-lg shadow-2xl">
		<!-- <figure class="rounded-t-lg ">
			<img class="h-[170px] w-full rounded-t-lg" src={country.flags.png}  alt={country.flags.alt} >
		</figure> -->
		<a href="/detail/{nameCountry}">
			<ImageLazy countryFlag={country.flags.svg} countryAlt={country.flags.alt}/>
			<article class="flex flex-col mb-9">
				<h2 class="mx-6 mt-6 mb-4">{country.name.common}</h2>
				<p class="mx-6 mb-1"><span class=" mr-1 mb-4">Population: </span> {country.population.toLocaleString('en-US')}</p>
				<p class="mx-6 mb-1"><span class=" mr-1 mb-4">Region: </span> {country.region}</p>
				<p class="mx-6 mb-1"><span class=" mr-1 mb-4">Capital: </span> {country["capital"]}</p>
			</article>
		</a>
	</button>
</div>
<style>
	h2{
		font-weight: 800;
		font-size:17px;
		text-align: left;
	}
	span{
		text-align: left;
		font-weight: 800;
		font-size: 15px;
	}
	p{
		text-align: left;
		font-size: 14px;
	}
</style>
