// src/lib/List_search.svelte
<script>
	import ListContinents from './List_continents.svelte';
	import Search from './Search.svelte';
</script>

<div class="container__submenu lg:h-[100px] h-[180px] bg-menu-color-light dark:bg-color-dark">
	<div class="container__submenu--items flex lg:flex-row flex-col justify-between">
		<Search on:search/>
		<div>
			<ListContinents on:select/>
		</div>
	</div>
</div>
<style>
	.container__submenu{
		width: 100%;
	}
	.container__submenu--items{
		padding-top: 20px;
		padding-left: 16px;
		padding-right: 16px;
	}


</style>

// src/presentation/components/ListSearch.vue
<script setup lang="ts">
import { ref } from 'vue';
import Search from './Search.vue';
import ListContinents from './ListContinents.vue';
import CountryBody from './CountryBody.vue';

const query = ref('');
const region = ref('');

const handleSearch = (q: string) => {
  query.value = q;
};

const handleSelect = (r: string) => {
  if (region.value && r !== region.value) {
    query.value = '';
  }
  region.value = r;
};
</script>

<template>
  <div class="w-full bg-surface border-b border-muted/10">
    <div class="max-w-[1400px] mx-auto py-6 px-5 lg:px-8 flex flex-col md:flex-row gap-4 items-stretch md:items-center justify-between">
      <div class="flex-1 min-w-[280px] max-w-full md:max-w-[420px]">
        <Search @search="handleSearch" />
      </div>
      <div class="min-w-[180px] w-full md:w-auto">
        <ListContinents @select="handleSelect" />
      </div>
    </div>
  </div>
  <CountryBody :query="query" :region="region" />
</template>
